doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
#        driver: 'pdo_mysql'
        driver: 'pdo_pgsql'
        server_version: '12.2'
        charset: utf8
        default_table_options:
            charset: utf8
            collate: -

        types:
            user_user_email: 'App\Model\User\Domain\Types\EmailType'
            user_user_id: 'App\Model\User\Domain\Types\IdType'
            user_user_role: 'App\Model\User\Domain\Types\RoleType'
            product_id: 'App\Model\Product\Domain\Types\IdType'
            brand_id: 'App\Model\Brand\Domain\Types\IdType'
            category_id: 'App\Model\Category\Domain\Types\IdType'
            product_status: 'App\Model\Product\Domain\Types\StatusType'
            category_status: 'App\Model\Category\Domain\Types\StatusType'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            User:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Model/User/Domain/Entity'
                prefix: 'App\Model\User\Domain\Entity'
                alias: User
            Status:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Model/User/Domain/ValueObject'
                prefix: 'App\Model\User\Domain\ValueObject'
                alias: Status

            Product:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Model/Product/Domain/Entity'
                prefix: 'App\Model\Product\Domain\Entity'
                alias: Product

            Brand:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Model/Brand/Domain/Entity'
                prefix: 'App\Model\Brand\Domain\Entity'
                alias: Brand

            Category:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Model/Category/Domain/Entity'
                prefix: 'App\Model\Category\Domain\Entity'
                alias: Category

            Price:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Model/Product/Domain/ValueObject'
                prefix: 'App\Model\Product\Domain\ValueObject'
                alias: Price
