# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    uploads_dir_name: 'uploads'
    uploads_base_url: '%env(SITE_BASE_URL)%/%uploads_dir_name%'
    template_dir_path: '%kernel.project_dir%/templates'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

        bind:
            $uploadedAssetsBaseUrl: '%uploads_base_url%'
            $uploadsFilesystem: '@oneup_flysystem.public_uploads_filesystem_filesystem'
            $resetPasswordEmailTemplate: 'email/reset_password_confirm.html.twig'
            $signUpConfirmTemlate: 'email/signup.confirm.html.twig'
            $changeEmailConfirmTemplate: 'email/change_email_confirm.html.twig'
    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Repository\UserRepository: ~
    App\Service\Auth\VerificationTokenizerFactory: ~

    App\Model\User\Domain\Service\TokenSender $verificationSender: '@App\Service\Auth\VerificationTokenSender'
    App\Model\User\Domain\Service\ITokenizer $verificationTokenizer: '@App\Service\Auth\VerificationTokenizer'
    App\Model\User\Domain\Service\IHasher $passwordHasher: '@App\Service\Auth\PasswordHasher'
    App\Model\User\Domain\Service\IAvatarUploader $avatarUploader: '@App\Service\Upload\UserAvatarUpload'

    App\Service\Auth\VerificationTokenizer:
        factory: 'App\Service\Auth\VerificationTokenizerFactory::create'
        arguments: ['PT1H']

    Symfony\Component\Asset\Context\RequestStackContext: '@assets.context'

